# Generated by Django 3.2.3 on 2021-05-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[(1, 'Auto'), (2, 'Beauty'), (4, 'Garden'), (5, 'Grocery'), (6, 'Outdoors'), (7, 'Pet'), (8, 'Tech')], default=8, max_length=1)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
    ]
