# Generated by Django 3.2.3 on 2021-05-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0010_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
