# Generated by Django 3.2.3 on 2021-05-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
        ('productapp', '0026_remove_product_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer'),
            preserve_default=False,
        ),
    ]
