# Generated by Django 3.2.4 on 2021-06-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('department', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03')], default='01', max_length=2)),
            ],
        ),
    ]
