# Generated by Django 3.2.3 on 2021-05-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('1', 'Auto'), ('2', 'Beauty'), ('3', 'Groceries'), ('4', 'Outdoors'), ('5', 'Tech')], default='5', max_length=1)),
            ],
        ),
    ]
