# Generated by Django 3.2.3 on 2021-05-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0018_auto_20210527_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='productapp.Category'),
        ),
    ]
