# Generated by Django 3.2.3 on 2021-05-27 07:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0019_auto_20210527_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, help_text='Select a genre for this book', on_delete=django.db.models.deletion.CASCADE, to='productapp.category'),
            preserve_default=False,
        ),
    ]
